// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjltywepybuznrmctglq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbHR5d2VweWJ1em5ybWN0Z2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTIwMzQsImV4cCI6MjA1NDU4ODAzNH0.iZZx4QNlP2y8l-YeixHi93uwT8yWYZki2BMoBxyQtP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);